#Script to generate figure 1, based on the results generated by the simulation.R script.
library(ggplot2)
library(tidyr)
library(dplyr)
library(gridExtra)
library(ggtext)

data <- c()
nsim <- 50
nlong <- c(500, 1000, 1500, 2000)
sparse_long <- c(1, 2, 3)
K_ranges <- 1:10

# Aim: Plot loss for various levels of K.
# Final figure: 2 x 4 panels (rows = Method, cols = n)

len_report <- length(nlong) * length(sparse_long) * length(K_ranges)

# ---- report stores mean and sd for both methods (7 columns) ----
report <- data.frame(matrix(0, nrow = len_report, ncol = 7))
colnames(report) <- c("K", "n", "sparse_lv",
                      "loss_mean", "loss_sd",
                      "loss_BT_mean", "loss_BT_sd")

z <- 0

for (sparse_lv in sparse_long) {
  for (n in nlong) {
    for (k in K_ranges) {
      z <- z + 1
      # Get relevant results
      load(sprintf("slv%dnsim%dn%dK%d.Rdata", sparse_lv, nsim, n, k))
      report[z, ] <- c(
        k, n, sparse_lv,
        mean(out$Totalloss),     sd(out$Totalloss),
        mean(out$Totalloss_BT),  sd(out$Totalloss_BT)
      )
    }
  }
}

# Step 1: Reshape to long format, keeping mean+sd together
report_long <- report %>%
  pivot_longer(
    cols = c("loss_mean", "loss_BT_mean", "loss_sd", "loss_BT_sd"),
    names_to = c("Method", ".value"),
    names_pattern = "(loss|loss_BT)_(mean|sd)"
  )

# Step 2: Update factor levels and labels + compute mean ± 2SD bounds
report_long <- report_long %>%
  mutate(
    K = as.integer(K),
    n = factor(n, levels = c(500, 1000, 1500, 2000)),
    sparse_lv = factor(sparse_lv),
    Method = factor(Method, levels = c("loss", "loss_BT"),
                    labels = c("Proposed", "BT")),
    Loss = mean,
    Loss_low  = mean - 2 * sd,
    Loss_high = mean + 2 * sd
  )

#plotting
ggplot(report_long,
       aes(x = K, y = Loss,
           color = sparse_lv,
           linetype = sparse_lv,
           group = sparse_lv)) +
  
  geom_line(linewidth = 0.7) +
  #error bars
  geom_errorbar(
    aes(ymin = Loss_low, ymax = Loss_high),
    width = 0.30,
    linewidth = 1.0,
    linetype = "solid",     
    show.legend = FALSE
  ) +
  
  facet_grid(Method ~ n,
             labeller = labeller(n = function(x) paste0("n = ", x))) +
  
  labs(
    title = "Loss Comparison by Sparsity Level and Sample Size",
    x = "K",
    y = "Mean Loss",
    color = "Sparsity Level",
    linetype = "Sparsity Level"
  ) +
  
  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(size = 12),
    legend.position = "bottom",
    legend.box = "horizontal",
    panel.spacing = unit(1.1, "lines"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  ) +
  
  scale_color_manual(
    values = c("1" = "#1b9e77", "2" = "#d95f02", "3" = "#7570b3"),
    labels = c("Sparse", "Less Sparse", "Dense")
  ) +
  
  scale_linetype_manual(
    values = c("1" = "dotted", "2" = "dashed", "3" = "solid"),
    labels = c("Sparse", "Less Sparse", "Dense")
  ) +
  
  scale_x_continuous(
    breaks = K_ranges,
    minor_breaks = NULL
  )